# Generated by Django 5.2.7 on 2026-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('game', 'Game'), ('tv', 'TV Show')], max_length=10),
        ),
    ]
