# Generated by Django 5.2.7 on 2025-10-28 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediahub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('watched', 'Watched'), ('played', 'Played'), ('downloaded', 'Downloaded'), ('liked', 'Liked'), ('rated', 'Rated')], max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mediaitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='mediahub.mediaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
